apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo2-dev
  namespace: wego-system
resources:
- app.yaml
- demo2-dev-gitops-deploy.yaml
- demo2-dev-gitops-source.yaml
